on:
  workflow_call:
    inputs:
      environment:
        description: The GitHub environment to use
        type: string
        required: true
    secrets:
      ZPA_CLIENT_ID:
        required: true
      ZPA_CLIENT_SECRET:
        required: true
      ZPA_CUSTOMER_ID:
        required: true
      ZPA_CLOUD:
        required: true
      ZSCALER_SDK_TEST_SWEEP:
        required: true

jobs:
  zpa-test:
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go${{ matrix.go-version }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
      - name: Run tests with retry
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 10  # Adjust as needed
          command: |
            make test:unit:zpa
            make test:integration:zpa
        env:
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
          ZPA_CLOUD: ${{ secrets.ZPA_CLOUD }}
          ZSCALER_SDK_TEST_SWEEP: ${{ secrets.ZSCALER_SDK_TEST_SWEEP }}
