on:
    workflow_call:
      inputs:
        environment:
          description: The GitHub environment to use
          type: string
          required: true
      secrets:
        ZCON_USERNAME:
          required: true
        ZCON_PASSWORD:
          required: true
        ZCON_API_KEY:
          required: true
        ZCON_CLOUD:
          required: true
        ZSCALER_SDK_TEST_SWEEP:
          required: true

jobs:
  zcon-test:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.19", "1.20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVersion }}

      - name: Set Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Pull external libraries
        run: make vendor

      - name: Run tests with retry on Ubuntu
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 20  # Adjust as needed
          command: |
            make test:integration:zcon
            make zconActivator
        env:
          ZCON_USERNAME: ${{ secrets.ZCON_USERNAME }}
          ZCON_PASSWORD: ${{ secrets.ZCON_PASSWORD }}
          ZCON_API_KEY: ${{ secrets.ZCON_API_KEY }}
          ZCON_CLOUD: ${{ secrets.ZCON_CLOUD }}
          ZSCALER_SDK_TEST_SWEEP: ${{ secrets.ZSCALER_SDK_TEST_SWEEP }}
