name: Sanity Check
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.18, 1.19]

    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go get -v -t -d ./zpa
        go get -v -t -d ./zia
        go get -v -t -d ./zdx
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Run unittests
      run: |
        go test ./zpa/
        go test ./zia/
        go test ./zdx/

    - name: Build
      run: |
        go build -v ./zpa/
        go build -v ./zia/
        go build -v ./zdx/
