name: ZIdentity Test
on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - master

  schedule:
    - cron: '0 11 * * 1-5' # UTC
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

  # For systems with an upstream API that could drift unexpectedly (like most SaaS systems, etc.),
  # we recommend testing at a regular interval not necessarily tied to code changes. This will
  # ensure you are alerted to something breaking due to an API change, even if the code did not
  # change.


jobs:
  zidentity-zsbeta-tests:
    environment: ZIDENTITY_BETA
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: ["1.24"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVersion }}

      - name: Clean existing Go modules
        run: go clean -modcache

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: go mod download

      - name: Run tests with retry on Ubuntu
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 20 # Adjust as needed
          command: |
            make sweep:zidentity
            make test:integration:zidentity
        env:
          ZSCALER_CLIENT_ID: ${{ secrets.ZSCALER_CLIENT_ID }}
          ZSCALER_CLIENT_SECRET: ${{ secrets.ZSCALER_CLIENT_SECRET }}
          ZSCALER_VANITY_DOMAIN: ${{ secrets.ZSCALER_VANITY_DOMAIN }}
          ZSCALER_CLOUD: ${{ secrets.ZSCALER_CLOUD }}
          ZIDENTITY_SDK_TEST_SWEEP: ${{ secrets.ZIDENTITY_SDK_TEST_SWEEP }}

      - name: Publish test coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out 
          fail_ci_if_error: true
